import { jsPDF } from "jspdf";
import { scoringConfig } from "../scoring/config";
import type { ScoreResult } from "../scoring/types";

type PdfReportInput = {
  page: {
    keyword: string;
    location: string;
    url: string;
    title: string;
    metaDescription: string;
  };
  result: ScoreResult;
};

const logoUrl =
  "https://cwccomputerrepairchard.com/wp-content/uploads/2024/02/CWC-Logo-image-1-e1777727757742.png";

const categoryLabels: Record<keyof ScoreResult["categoryScores"], string> = {
  content: "Content",
  headings: "Headings",
  metadata: "Metadata",
  localSignals: "Local signals",
  trust: "Trust",
  conversion: "Conversion",
  schema: "Schema"
};

function createPdfFileName(url: string): string {
  try {
    const parsedUrl = new URL(url);
    return `${parsedUrl.hostname.replace(/^www\./, "")}-branded-seo-report.pdf`;
  } catch {
    return "local-seo-branded-report.pdf";
  }
}

function getTopIssues(result: ScoreResult): string[] {
  if (result.weaknesses.length > 0) {
    return result.weaknesses.slice(0, 3);
  }

  if (result.missingItems.length > 0) {
    return result.missingItems.slice(0, 3);
  }

  if (result.prioritizedActions.length > 0) {
    return result.prioritizedActions.slice(0, 3).map((action) => action.action);
  }

  return [
    "No major issues found. Review recommended actions for optional improvements."
  ];
}

async function loadImageAsDataUrl(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);

    if (!response.ok) {
      return null;
    }

    const blob = await response.blob();

    return await new Promise((resolve) => {
      const reader = new FileReader();

      reader.onloadend = () => {
        resolve(typeof reader.result === "string" ? reader.result : null);
      };
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export async function generatePdfReport({ page, result }: PdfReportInput) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 44;
  const contentWidth = pageWidth - margin * 2;
  const green = "#166534";
  const dark = "#102019";
  const muted = "#607166";
  const lightGreen = "#edf9f1";
  let y = 44;

  function addFooter() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(muted);
    doc.text("Generated by Local SEO Scoring App", margin, pageHeight - 24);
  }

  function addPageIfNeeded(requiredHeight: number) {
    if (y + requiredHeight <= pageHeight - 52) {
      return;
    }

    addFooter();
    doc.addPage();
    y = 44;
  }

  function addWrappedText(
    text: string,
    options: {
      color?: string;
      fontSize?: number;
      fontStyle?: "normal" | "bold";
      indent?: number;
      lineGap?: number;
      width?: number;
    } = {}
  ) {
    const fontSize = options.fontSize ?? 10;
    const indent = options.indent ?? 0;
    const width = options.width ?? contentWidth - indent;
    const lines = doc.splitTextToSize(text || "Not provided.", width);
    const lineHeight = fontSize + (options.lineGap ?? 4);

    addPageIfNeeded(lines.length * lineHeight + 4);
    doc.setFont("helvetica", options.fontStyle ?? "normal");
    doc.setFontSize(fontSize);
    doc.setTextColor(options.color ?? dark);
    doc.text(lines, margin + indent, y);
    y += lines.length * lineHeight + 4;
  }

  function addSectionTitle(title: string) {
    addPageIfNeeded(34);
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(green);
    doc.text(title.toUpperCase(), margin, y);
    y += 18;
  }

  function addBulletList(items: string[], emptyText = "Nothing found.") {
    if (items.length === 0) {
      addWrappedText(emptyText, { color: muted });
      return;
    }

    items.forEach((item) => {
      addWrappedText(`- ${item}`, { indent: 8 });
    });
  }

  const logoDataUrl = await loadImageAsDataUrl(logoUrl);

  doc.setFillColor(green);
  doc.roundedRect(margin, y, contentWidth, 86, 16, 16, "F");

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, "PNG", margin + 20, y + 23, 76, 36);
  } else {
    doc.setFillColor("#ffffff");
    doc.roundedRect(margin + 20, y + 22, 74, 38, 8, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(green);
    doc.text("CWC", margin + 44, y + 46);
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor("#ffffff");
  doc.text("Local SEO Page Report", margin + 116, y + 36);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Client-facing SEO summary and action report", margin + 116, y + 56);
  y += 112;

  doc.setFillColor(lightGreen);
  doc.roundedRect(margin, y, contentWidth, 96, 14, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(46);
  doc.setTextColor(green);
  doc.text(String(result.totalScore), margin + 20, y + 56);
  doc.setFontSize(13);
  doc.text("/100", margin + 88, y + 56);
  doc.setFontSize(10);
  doc.setTextColor(muted);
  doc.text("Total score", margin + 22, y + 76);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(34);
  doc.setTextColor(dark);
  doc.text(result.grade, pageWidth - margin - 74, y + 54);
  doc.setFontSize(10);
  doc.setTextColor(muted);
  doc.text("Grade", pageWidth - margin - 78, y + 76);
  y += 122;

  addSectionTitle("Page details");
  addWrappedText(`Target keyword: ${page.keyword || "Not provided."}`);
  addWrappedText(`Location: ${page.location || "Not provided."}`);
  addWrappedText(`URL: ${page.url || "Not provided."}`);
  addWrappedText(`Page title: ${page.title || "Not provided."}`);
  addWrappedText(`Meta description: ${page.metaDescription || "Not provided."}`);

  addSectionTitle("Category scores");
  Object.entries(result.categoryScores).forEach(([key, score]) => {
    const category = key as keyof ScoreResult["categoryScores"];
    const maxScore = scoringConfig.categoryWeights[category];
    const barWidth = 220;
    const filledWidth = Math.min((score / maxScore) * barWidth, barWidth);

    addPageIfNeeded(30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(dark);
    doc.text(categoryLabels[category], margin, y);
    doc.setTextColor(green);
    doc.text(`${score} / ${maxScore}`, margin + 160, y);
    doc.setFillColor("#e8f0e8");
    doc.roundedRect(margin + 240, y - 8, barWidth, 8, 4, 4, "F");
    doc.setFillColor(green);
    doc.roundedRect(margin + 240, y - 8, filledWidth, 8, 4, 4, "F");
    y += 24;
  });

  addSectionTitle("Top issues found");
  addBulletList(getTopIssues(result));

  addSectionTitle("Recommended actions");
  if (result.prioritizedActions.length === 0) {
    addWrappedText("No recommended actions found.", { color: muted });
  } else {
    result.prioritizedActions.forEach((action) => {
      addWrappedText(`${action.priority.toUpperCase()} PRIORITY`, {
        color: green,
        fontSize: 9,
        fontStyle: "bold"
      });
      addWrappedText(action.action, { fontStyle: "bold" });
      addWrappedText(action.whyItMatters, { color: muted });
      addWrappedText(`Estimated score gain: +${action.estimatedScoreGain}`, {
        color: green,
        fontStyle: "bold"
      });
      y += 4;
    });
  }

  addSectionTitle("Strengths");
  addBulletList(result.strengths);

  addSectionTitle("Weaknesses");
  addBulletList(result.weaknesses);

  addSectionTitle("Missing items");
  addBulletList(result.missingItems);

  addSectionTitle("Evidence items");
  addBulletList(result.evidenceItems);

  addFooter();
  doc.save(createPdfFileName(page.url));
}
